## Numpy Array Operations

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basis Slicing", arr[2:7])
print("With Step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basis Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific Element",arr_2d[1, 2])
print("Entire Row",arr_2d[1])
print("Entire Column",arr_2d[:,1])

Specific Element 6
Entire Row [4 5 6]
Entire Column [2 5 8]


## Sorting

In [6]:
unsorted = np.array([1,4,2,3,5,7])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                           [1,2],
                           [2,4]])
print("Sorted 2d Array by column",np.sort(arr_2d_unsorted, axis=0)) #Mostly used

print("Sorted 2d Array by row",np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 2 3 4 5 7]
Sorted 2d Array by column [[1 1]
 [2 2]
 [3 4]]
Sorted 2d Array by row [[1 3]
 [1 2]
 [2 4]]


## Filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0] # Expressions --> There is some output(Complete Logic)
print("Even numbers",even_numbers)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexin vs np.where()

In [12]:
indices = [0, 2, 4]
print(numbers[indices])
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, "true", "false") # x and y value(numbers *4 and numbers) (condition, true, false)
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
# if(numbers>5):
#     numbers*4
# else:
#     numbers

### Adding and Removing data

In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# combined = arr1 + arr2  # Will add values
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Conpatibility shapes",a.shape == b.shape)

Conpatibility shapes False


In [24]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original, new_row)) # Adds new row(vstack)
new_col = np.array([[4],[5]])
with_new_column = np.hstack((original,new_col))
print(original)
print(with_new_row)
print(with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 4]
 [3 4 5]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted) # it returns array after deletion not element

Array after deletion:  [1 2 4 5]
