# Numpy Preparation

In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

## Creating numpy arrays

In [3]:
arr_1d = np.array([1,2,3])
print("1d Array: ",arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d Array: ",arr_2d)

1d Array:  [1 2 3]
2d Array:  [[1 2 3]
 [4 5 6]]


### List VS numpy arrays

In [6]:
py_list = [1,2,3]
print("Multiplication of python list: ",py_list * 2)
numpy_arr = np.array([1,2,3])
print("Multiplication of numpy array: ",numpy_arr * 2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n Time taken by list: ",time.time() - start)

start = time.time()
numpy_arr = np.arange(100000) * 2
print("\n Time taken by array: ",time.time() - start)

Multiplication of python list:  [1, 2, 3, 1, 2, 3]
Multiplication of numpy array:  [2 4 6]

 Time taken by list:  0.006894826889038086

 Time taken by array:  0.005723714828491211


### Creating numpy arrays from scratch

In [3]:
zeros = np.zeros((2,3))
print("Zero Array: \n",zeros)

ones = np.ones((2,3))
print("One Array: \n",ones)

full = np.full((2,2),7)
print("Full Array: \n",full)

random = np.random.random((2,3))
print("Random Array: \n",random)

sequence = np.arange(0,10,2)
print("Sequence Array: \n",sequence)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
One Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.59897369 0.31709209 0.40110848]
 [0.04722929 0.55678065 0.4128134 ]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1,3,4])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #Multi-dimensional Arrays
print("Tensor: ",tensor)

Vector:  [1 3 4]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [7]:
arr = np.array([[1,2,3],
                [4,5,True]]) # Not ideal presentation-Must haave similar data but it does no give error
print("Shape ", arr.shape)
print("Dimension ",arr.ndim)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
DType  int64


### Array Reshaping

In [12]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# Ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled Array: ",raveled)

# Transpose
transpose = reshaped.T
print("\nTransposed array: ",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
